git:
  depth: 3
env:
  global:
  - secure: "AzM98HKS2RDP+/WdvsFiEqTbVPwLBEAtNXDQPR7cV1gAEZoNhri/iINnRAHtECgVQDt2gKmxEiyOA07zMKPpt5PwhoyZUnICwxl1t2FOkTL4LlfI+3ew1rf4F8wmaSQX/BRT7b3IgyEI0RFRCow8KH49X8xdEtAFYJB3YFu2Y6M="
  - secure: "BDNmD9y3mdZEQoFgXW2dC1FawofkThFwbITidMqeKLxSstNxQGKCpxOFAV604kaTGsf7ihpdm8WYE5IjHKTaoewdQ9hLXZPtswWXq5Ebe2gKHqJVNZa2bFD6hQBD2S7BLWWeAVIoLkyfV/QLnplOquUZTXWZ3TW2A+IXzQE+AnE="
  - AWS_DEFAULT_REGION: "us-east-1"
  - JDK_LINUX: https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-fx-jdk8.0.232-linux_x64.tar.gz
  - JDK_MACOS: https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-fx-jdk8.0.232-macosx_x64.tar.gz

matrix:
  include:

  # -----------------
  - name: "Nightly"
  # -----------------
    dist: bionic
    language: java
    jdk: openjdk11

    addons:
      apt:
        packages:
        - ant

    before_install:
    - export PATH=$PATH:$HOME/.local/bin
    - openssl aes-256-cbc -K $encrypted_c66606bfdf5f_key -iv $encrypted_c66606bfdf5f_iv -in .travis.tar.enc -out .travis.tar -d
    - tar xvf .travis.tar

    script:
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/id_rsa_release_travis
    - ssh-add .travis/id_rsa_release_travis
    - export LWJGL_BUILD_TYPE=nightly
    - export LWJGL_BUILD_ARCH=ppc64le
    - curl $JDK_LINUX --output jdk8.tar.gz
    - mkdir jdk8 && tar xf jdk8.tar.gz -C jdk8 --strip-components 1
    - ant init
    - JAVA8_HOME=$TRAVIS_BUILD_DIR/jdk8 ant compile-templates
    - JAVA8_HOME=$TRAVIS_BUILD_DIR/jdk8 ant generate
    - JAVA8_HOME=$TRAVIS_BUILD_DIR/jdk8 ant compile
    - JAVA8_HOME=$TRAVIS_BUILD_DIR/jdk8 ant release
    - cd bin/RELEASE
    - git init
    - git remote add origin git@github.com:EMue/lwjgl3-release.git
    - git fetch origin e444de584971bb3e5d6c46032843995821493482
    - git checkout e444de584971bb3e5d6c46032843995821493482
    - git branch nightly-ppc64le_64kpages
    - git checkout nightly-ppc64le_64kpages
    - git add *
    - git commit -m "Deploy nightly release from Travis CI."
    - git push --force origin nightly-ppc64le_64kpages
