git:
  depth: 3
env:
  global:
  - secure: "AzM98HKS2RDP+/WdvsFiEqTbVPwLBEAtNXDQPR7cV1gAEZoNhri/iINnRAHtECgVQDt2gKmxEiyOA07zMKPpt5PwhoyZUnICwxl1t2FOkTL4LlfI+3ew1rf4F8wmaSQX/BRT7b3IgyEI0RFRCow8KH49X8xdEtAFYJB3YFu2Y6M="
  - secure: "BDNmD9y3mdZEQoFgXW2dC1FawofkThFwbITidMqeKLxSstNxQGKCpxOFAV604kaTGsf7ihpdm8WYE5IjHKTaoewdQ9hLXZPtswWXq5Ebe2gKHqJVNZa2bFD6hQBD2S7BLWWeAVIoLkyfV/QLnplOquUZTXWZ3TW2A+IXzQE+AnE="
  - AWS_DEFAULT_REGION: "us-east-1"
  - JDK_LINUX: https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-fx-jdk8.0.232-linux_x64.tar.gz
  - JDK_MACOS: https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-fx-jdk8.0.232-macosx_x64.tar.gz

matrix:
  include:

  # -----------------
  - name: "Linux ppc64le"
  # -----------------
    dist: xenial
    language: java
    jdk: openjdk8

    addons:
      apt:
        packages:
        - ant
        - gcc-4.8-powerpc64le-linux-gnu
        - g++-4.8-powerpc64le-linux-gnu
        - gcc-4.9-powerpc64le-linux-gnu
        - g++-4.9-powerpc64le-linux-gnu
        - libc6-dev-ppc64el-cross

    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - sudo sed -i 's/deb http/deb [arch=amd64,i386] http/' /etc/apt/sources.list
    - sudo grep "ubuntu.com/ubuntu" /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's/amd64,i386/ppc64el,ppc64el/' /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's#http://.*/ubuntu#http://ports.ubuntu.com/ubuntu-ports#' /etc/apt/sources.list.d/ports.list
    - sudo dpkg --add-architecture ppc64el
    - sudo apt-get update || true
    - sudo apt-get -yq install libglu-dev:ppc64el libgl1-mesa-glx:ppc64el libx11-dev:ppc64el -o Dpkg::Options::="--force-overwrite"
    - openssl aes-256-cbc -K $encrypted_c66606bfdf5f_key -iv $encrypted_c66606bfdf5f_iv -in .travis.tar.enc -out .travis.tar -d
    - tar xvf .travis.tar

    script:
    - eval "$(ssh-agent -s)"
    - chmod 600 .travis/id_rsa_deploy_travis
    - ssh-add .travis/id_rsa_deploy_travis
    - export LWJGL_BUILD_TYPE=nightly
    - export LWJGL_BUILD_ARCH=ppc64le
    - curl $JDK_LINUX --output jdk8.tar.gz
    - mkdir jdk8 && tar xf jdk8.tar.gz -C jdk8 --strip-components 1
    - JAVA_HOME=$TRAVIS_BUILD_DIR/jdk8 ant compile-templates upload-native -Dgcc.version=4.8 -Dgcc.libpath.opengl=/usr/lib/powerpc64le-linux-gnu/mesa
    - cd deploy
    - git init
    - git remote add origin git@github.com:EMue/lwjgl3-bin.git
    - git fetch origin 0449e44c07e2bdf09e79f21c75a92f7d94b0e496
    - git checkout 0449e44c07e2bdf09e79f21c75a92f7d94b0e496
    - git branch ppc64le_nightly_lwjgl3
    - git checkout ppc64le_nightly_lwjgl3
    - git add *
    - git commit -m "Deploy lwjgl3 from Travis CI."
    - git push --force origin ppc64le_nightly_lwjgl3
